### ISSUE TITLE
To-do

### ISSUE THREAD

**Issue by gabrielimartins7** [gabrielimartins7/Flappy-bird#1]
**Criar estrutura inicial do  jogo:**

---

- [ ] Setup inicial do canvas
- [ ] Desenhar o Flappy Bird na tela
- [ ] Game Loop
- [ ] Desenhar o resto do cenário
- [ ] Adicionar tela de início
